#!/bin/bash

set -eu

PIP_COMPILE_IMAGE='graph-notebook-docker-pip-compile:latest'

if [ $# -ne 2 ]; then
    echo "usage: $0 <requirements.in> <requirements.txt>" >&2
    exit 2
fi
REQ_IN=$(realpath "$1")
REQ_TXT=$(realpath "$2")

# Set working directory to the root of the repo.
cd "$(dirname $0)/.."

export DOCKER_BUILDKIT=1

docker build \
	--target pip-compile \
	-t "${PIP_COMPILE_IMAGE}" \
	.

docker run \
	--rm \
	-v "${REQ_IN}:/requirements.in:ro" \
	"${PIP_COMPILE_IMAGE}" \
	--output-file=- /requirements.in > "${REQ_TXT}"
